events { worker_connections 1024; }

http {
    # Định nghĩa upstream cho Load Balancer (Round Robin mặc định)
    upstream api_backend {
        server api_node_1:8080;
        server api_node_2:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://api_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}